mpls:
  ip: true
  ldp:
    interface_disabled_default: true
    router_id: 192.168.1.1
    shutdown: false
    transport_address_interface: Loopback0
  icmp:
    fragmentation_needed_tunneling: true
  rsvp:
    hello:
      interval: 30
      multiplier: 254
    authentication:
      password_indexes:
        - index: 766
          password_type: 7
          password: SiMpLePaSs
        - index: 55
          password_type: '7'
          password: SiMpLePaSsInDeX
      active_index: 766
      sequence_number_window: 234
      type: md5
    fast_reroute:
      mode: link-protection
      reversion: local
      bypass_tunnel_optimization_interval: 65535
    graceful_restart:
      role_helper:
        enabled: true
        grace_period_recovery: 32
        grace_period_restart: 33
      role_speaker:
        enabled: true
        grace_period_recovery: 35
        grace_period_restart: 36
    hitless_restart:
      enabled: true
      timer_recovery: 222
    ip_access_group: RSVP_access_group_ipv4
    ipv6_access_group: RSVP_access_group_ipv6
    label_local_termination: explicit-null
    mtu_signaling: true
    p2mp_enabled: false
    preemption_method:
      preemption: soft
      timer: 444

ethernet_interfaces:
  - name: Ethernet1
    switchport:
      enabled: false
    ip_address: 192.168.100.1/31
    mpls:
      ip: true
      ldp:
        interface: true
        igp_sync: true

loopback_interfaces:
  - name: Loopback0
    ip_address: 192.168.1.1/32
    mpls:
      ldp:
        interface: true
